name: Jarrett
url: https://github.com/JarrettW
description: One must work and dare if one really wants to live.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
